# Generated by Django 6.0.4 on 2026-04-21 22:17

import apps.core.models
import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=160, unique=True)),
                ('phone', models.CharField(blank=True, max_length=40)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CustomerNode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=160, unique=True)),
                ('contact_name', models.CharField(blank=True, max_length=120)),
                ('phone', models.CharField(blank=True, max_length=40)),
                ('address', models.TextField(blank=True)),
                ('credit_limit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
                'constraints': [models.CheckConstraint(condition=models.Q(('credit_limit__gte', 0)), name='customer_credit_limit_gte_0')],
            },
        ),
        migrations.CreateModel(
            name='CustomerPayment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('received_at', models.DateTimeField(db_index=True)),
                ('method', models.CharField(max_length=40)),
                ('reference', models.CharField(blank=True, max_length=120)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='core.customernode')),
            ],
            options={
                'ordering': ['-received_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(choices=[('A', 'Socio A'), ('B', 'Socio B')], max_length=1, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('initial_capital', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('ownership_percent', models.DecimalField(decimal_places=2, default=Decimal('50.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))])),
                ('active', models.BooleanField(default=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['code'],
            },
            bases=(apps.core.models.FullCleanOnSaveMixin, models.Model),
        ),
        migrations.CreateModel(
            name='OperationalExpense',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.CharField(max_length=80)),
                ('description', models.CharField(max_length=240)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('incurred_at', models.DateField(db_index=True)),
                ('voided', models.BooleanField(default=False)),
                ('paid_by_partner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expenses_paid', to='core.partner')),
            ],
            options={
                'ordering': ['-incurred_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PartnerPayout',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('paid_at', models.DateTimeField(db_index=True)),
                ('reason', models.CharField(choices=[('reimbursement', 'Reembolso'), ('profit', 'Utilidad'), ('capital_return', 'Retorno de capital')], max_length=40)),
                ('notes', models.TextField(blank=True)),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payouts', to='core.partner')),
            ],
            options={
                'ordering': ['-paid_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sku', models.CharField(max_length=40, unique=True)),
                ('name', models.CharField(max_length=160)),
                ('grams_per_piece', models.DecimalField(decimal_places=4, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.0001'))])),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['sku', 'active'], name='core_produc_sku_b6478b_idx')],
            },
        ),
        migrations.CreateModel(
            name='PortionSize',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=40)),
                ('pieces_per_portion', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('active', models.BooleanField(default=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='portions', to='core.product')),
            ],
            options={
                'ordering': ['product__name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='InventoryLot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lot_code', models.CharField(max_length=60, unique=True)),
                ('boxes_qty', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('bags_per_box', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('kg_per_bag', models.DecimalField(decimal_places=3, default=Decimal('1.000'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))])),
                ('box_cost', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('total_grams', models.DecimalField(decimal_places=3, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))])),
                ('remaining_grams', models.DecimalField(decimal_places=3, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.000'))])),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('purchased_at', models.DateField()),
                ('paid_by_partner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.partner')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lots', to='core.product')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.supplier')),
            ],
            options={
                'ordering': ['purchased_at', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='CustomerPrice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('active', models.BooleanField(default=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='core.customernode')),
                ('portion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.portionsize')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.product')),
            ],
            options={
                'ordering': ['customer__name', 'product__name', 'portion__name'],
            },
            bases=(apps.core.models.FullCleanOnSaveMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('draft', 'Borrador'), ('delivered', 'Entregada'), ('partial', 'Pago parcial'), ('paid', 'Pagada'), ('cancelled', 'Cancelada')], default='draft', max_length=20)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('due_at', models.DateTimeField(blank=True, null=True)),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('total_cogs', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('notes', models.TextField(blank=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales', to='core.customernode')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CustomerPaymentAllocation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sale_allocations', to='core.customerpayment')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_allocations', to='core.sale')),
            ],
            options={
                'ordering': ['created_at'],
            },
            bases=(apps.core.models.FullCleanOnSaveMixin, models.Model),
        ),
        migrations.CreateModel(
            name='SaleLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('portions_qty', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('pieces_per_portion_snapshot', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('grams_per_piece_snapshot', models.DecimalField(decimal_places=4, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.0001'))])),
                ('total_grams', models.DecimalField(decimal_places=3, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))])),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('line_total', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('cogs_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('portion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.portionsize')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.product')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='core.sale')),
            ],
            options={
                'ordering': ['created_at'],
            },
            bases=(apps.core.models.FullCleanOnSaveMixin, models.Model),
        ),
        migrations.CreateModel(
            name='InventoryAllocation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('grams', models.DecimalField(decimal_places=3, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))])),
                ('unit_cost_snapshot', models.DecimalField(decimal_places=6, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.000000'))])),
                ('cost_amount', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('lot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sale_allocations', to='core.inventorylot')),
                ('sale_line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_allocations', to='core.saleline')),
            ],
            options={
                'ordering': ['created_at'],
            },
            bases=(apps.core.models.FullCleanOnSaveMixin, models.Model),
        ),
        migrations.CreateModel(
            name='SmartSplitAllocation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(choices=[('expense_reimbursement', 'Reembolso de gasto'), ('inventory_reserve', 'Reserva de inventario'), ('partner_profit', 'Utilidad de socio')], max_length=40)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('expense', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.operationalexpense')),
                ('partner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.partner')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='smart_split_allocations', to='core.customerpayment')),
                ('sale_line', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.saleline')),
            ],
            options={
                'ordering': ['created_at'],
            },
            bases=(apps.core.models.FullCleanOnSaveMixin, models.Model),
        ),
        migrations.AddIndex(
            model_name='customerpayment',
            index=models.Index(fields=['customer', 'received_at'], name='core_custom_custome_d062e6_idx'),
        ),
        migrations.AddConstraint(
            model_name='customerpayment',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='customer_payment_amount_gt_0'),
        ),
        migrations.AddConstraint(
            model_name='partner',
            constraint=models.CheckConstraint(condition=models.Q(('initial_capital__gte', 0)), name='partner_initial_capital_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='partner',
            constraint=models.CheckConstraint(condition=models.Q(('ownership_percent__gte', 0), ('ownership_percent__lte', 100)), name='partner_ownership_0_100'),
        ),
        migrations.AddIndex(
            model_name='operationalexpense',
            index=models.Index(fields=['paid_by_partner', 'voided'], name='core_operat_paid_by_1faa32_idx'),
        ),
        migrations.AddConstraint(
            model_name='operationalexpense',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='expense_amount_gt_0'),
        ),
        migrations.AddIndex(
            model_name='partnerpayout',
            index=models.Index(fields=['partner', 'reason'], name='core_partne_partner_95d8d9_idx'),
        ),
        migrations.AddConstraint(
            model_name='partnerpayout',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='partner_payout_amount_gt_0'),
        ),
        migrations.AddConstraint(
            model_name='portionsize',
            constraint=models.UniqueConstraint(condition=models.Q(('active', True)), fields=('product', 'name'), name='uniq_active_portion_per_product'),
        ),
        migrations.AddConstraint(
            model_name='customerprice',
            constraint=models.UniqueConstraint(condition=models.Q(('active', True)), fields=('customer', 'product', 'portion'), name='uniq_active_customer_price'),
        ),
        migrations.AddConstraint(
            model_name='customerprice',
            constraint=models.CheckConstraint(condition=models.Q(('unit_price__gte', 0)), name='customer_price_unit_gte_0'),
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['customer', 'status'], name='core_sale_custome_62d920_idx'),
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['delivered_at'], name='core_sale_deliver_07a52a_idx'),
        ),
        migrations.AddConstraint(
            model_name='sale',
            constraint=models.CheckConstraint(condition=models.Q(('total_amount__gte', 0)), name='sale_total_amount_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='sale',
            constraint=models.CheckConstraint(condition=models.Q(('total_cogs__gte', 0)), name='sale_total_cogs_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='customerpaymentallocation',
            constraint=models.UniqueConstraint(fields=('payment', 'sale'), name='uniq_payment_sale_allocation'),
        ),
        migrations.AddConstraint(
            model_name='customerpaymentallocation',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='payment_allocation_amount_gt_0'),
        ),
        migrations.AddIndex(
            model_name='saleline',
            index=models.Index(fields=['sale', 'product'], name='core_saleli_sale_id_22bb19_idx'),
        ),
        migrations.AddConstraint(
            model_name='saleline',
            constraint=models.CheckConstraint(condition=models.Q(('total_grams__gt', 0)), name='sale_line_total_grams_gt_0'),
        ),
        migrations.AddConstraint(
            model_name='saleline',
            constraint=models.CheckConstraint(condition=models.Q(('line_total__gte', 0)), name='sale_line_total_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='saleline',
            constraint=models.CheckConstraint(condition=models.Q(('cogs_amount__gte', 0)), name='sale_line_cogs_gte_0'),
        ),
        migrations.AddIndex(
            model_name='inventoryallocation',
            index=models.Index(fields=['lot', 'sale_line'], name='core_invent_lot_id_a585ca_idx'),
        ),
        migrations.AddConstraint(
            model_name='inventoryallocation',
            constraint=models.CheckConstraint(condition=models.Q(('grams__gt', 0)), name='inventory_alloc_grams_gt_0'),
        ),
        migrations.AddConstraint(
            model_name='inventoryallocation',
            constraint=models.CheckConstraint(condition=models.Q(('cost_amount__gte', 0)), name='inventory_alloc_cost_gte_0'),
        ),
        migrations.AddIndex(
            model_name='smartsplitallocation',
            index=models.Index(fields=['payment', 'type'], name='core_smarts_payment_4f541d_idx'),
        ),
        migrations.AddIndex(
            model_name='smartsplitallocation',
            index=models.Index(fields=['partner', 'type'], name='core_smarts_partner_bf4a65_idx'),
        ),
        migrations.AddConstraint(
            model_name='smartsplitallocation',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='smart_split_amount_gt_0'),
        ),
        migrations.AddConstraint(
            model_name='smartsplitallocation',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('expense__isnull', False), ('partner__isnull', False), ('sale_line__isnull', True), ('type', 'expense_reimbursement')), models.Q(('expense__isnull', True), ('partner__isnull', True), ('sale_line__isnull', False), ('type', 'inventory_reserve')), models.Q(('expense__isnull', True), ('partner__isnull', False), ('sale_line__isnull', True), ('type', 'partner_profit')), _connector='OR'), name='smart_split_type_shape_valid'),
        ),
        migrations.AddIndex(
            model_name='inventorylot',
            index=models.Index(fields=['product', 'remaining_grams', 'purchased_at'], name='core_invent_product_e15480_idx'),
        ),
        migrations.AddConstraint(
            model_name='inventorylot',
            constraint=models.CheckConstraint(condition=models.Q(('total_grams__gt', 0)), name='lot_total_grams_gt_0'),
        ),
        migrations.AddConstraint(
            model_name='inventorylot',
            constraint=models.CheckConstraint(condition=models.Q(('remaining_grams__gte', 0), ('remaining_grams__lte', models.F('total_grams'))), name='lot_remaining_valid'),
        ),
        migrations.AddConstraint(
            model_name='inventorylot',
            constraint=models.CheckConstraint(condition=models.Q(('total_cost__gte', 0)), name='lot_total_cost_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='inventorylot',
            constraint=models.CheckConstraint(condition=models.Q(('box_cost__gte', 0)), name='lot_box_cost_gte_0'),
        ),
    ]
