# Generated by Django 6.0.4 on 2026-04-21 23:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customernode',
            name='kind',
            field=models.CharField(choices=[('wholesale', 'Cliente mayorista'), ('direct', 'Venta directa')], db_index=True, default='wholesale', max_length=20),
        ),
        migrations.AddField(
            model_name='sale',
            name='channel',
            field=models.CharField(choices=[('wholesale', 'Mayoreo'), ('direct', 'Venta propia')], db_index=True, default='wholesale', max_length=20),
        ),
        migrations.AddField(
            model_name='sale',
            name='sold_by_partner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sales_made', to='core.partner'),
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['channel', 'status'], name='core_sale_channel_07aa3b_idx'),
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['sold_by_partner', 'delivered_at'], name='core_sale_sold_by_6a8521_idx'),
        ),
    ]
