# Generated by Django 6.0.4 on 2026-04-24 16:15

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_customernode_kind_sale_channel_sale_sold_by_partner_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='wholesale_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AddField(
            model_name='supplier',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='partner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supplier_profiles', to='core.partner'),
        ),
        migrations.AddIndex(
            model_name='supplier',
            index=models.Index(fields=['active', 'name'], name='core_suppli_active_811da7_idx'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.CheckConstraint(condition=models.Q(('wholesale_price__gte', 0)), name='product_wholesale_price_gte_0'),
        ),
    ]
