# Generated by Django 6.0.4 on 2026-04-25 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_backfill_sale_line_recovery'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='sale',
            new_name='core_sale_supplie_5c1886_idx',
            old_name='core_sale_supplie_2b2a34_idx',
        ),
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='name',
            field=models.CharField(max_length=160),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.UniqueConstraint(condition=models.Q(('active', True)), fields=('sku',), name='uniq_active_product_sku'),
        ),
        migrations.AddConstraint(
            model_name='supplier',
            constraint=models.UniqueConstraint(condition=models.Q(('active', True)), fields=('name',), name='uniq_active_supplier_name'),
        ),
    ]
