# Generated by Django 6.0.4 on 2026-04-25 02:34

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


def backfill_product_recovery_price(apps, schema_editor):
    Product = apps.get_model("core", "Product")
    PortionSize = apps.get_model("core", "PortionSize")

    def normalize(value):
        return (value or "").strip().lower().replace(" ", "").replace("-", "")

    for product in Product.objects.all():
        if product.wholesale_price and product.wholesale_price > 0:
            product.recovery_price = product.wholesale_price
            product.save(update_fields=["recovery_price"])
            continue

        identifiers = {normalize(product.sku), normalize(product.name)}
        portions = list(
            PortionSize.objects.filter(product=product, active=True, recovery_price__gt=0)
            .order_by("created_at", "name")
        )
        selected = None

        for portion in portions:
            portion_name = normalize(portion.name)
            if portion_name in identifiers or any(identifier and portion_name and portion_name in identifier for identifier in identifiers):
                selected = portion
                break

        if selected is None and portions:
            selected = portions[0]

        if selected is not None:
            product.recovery_price = selected.recovery_price
            product.save(update_fields=["recovery_price"])


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_rename_core_sale_supplie_2b2a34_idx_core_sale_supplie_5c1886_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='recovery_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.RunPython(backfill_product_recovery_price, noop_reverse),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.CheckConstraint(condition=models.Q(('recovery_price__gte', 0)), name='product_recovery_price_gte_0'),
        ),
    ]
