# Generated by Django 6.0.4 on 2026-04-27 18:37

import django.db.models.deletion
from django.db import migrations, models
from django.db.models import Count


def backfill_partner_ownership(apps, schema_editor):
    Partner = apps.get_model("core", "Partner")
    Product = apps.get_model("core", "Product")
    Supplier = apps.get_model("core", "Supplier")
    Sale = apps.get_model("core", "Sale")
    InventoryLot = apps.get_model("core", "InventoryLot")

    fallback_partner = Partner.objects.filter(active=True).order_by("code").first()
    fallback_partner_id = fallback_partner.id if fallback_partner else None

    for supplier in Supplier.objects.filter(partner__isnull=True):
        sale_owner = (
            Sale.objects.filter(supplier=supplier, sold_by_partner__isnull=False)
            .values("sold_by_partner")
            .annotate(total=Count("id"))
            .order_by("-total", "sold_by_partner")
            .first()
        )
        partner_id = (sale_owner or {}).get("sold_by_partner") or fallback_partner_id
        if partner_id:
            supplier.partner_id = partner_id
            supplier.save(update_fields=["partner"])

    for product in Product.objects.filter(partner__isnull=True):
        sale_owner = (
            Sale.objects.filter(lines__product=product, sold_by_partner__isnull=False)
            .values("sold_by_partner")
            .annotate(total=Count("id"))
            .order_by("-total", "sold_by_partner")
            .first()
        )
        lot_supplier_owner = (
            InventoryLot.objects.filter(product=product, supplier__partner__isnull=False)
            .values("supplier__partner")
            .annotate(total=Count("id"))
            .order_by("-total", "supplier__partner")
            .first()
        )
        lot_payer = (
            InventoryLot.objects.filter(product=product, paid_by_partner__isnull=False)
            .values("paid_by_partner")
            .annotate(total=Count("id"))
            .order_by("-total", "paid_by_partner")
            .first()
        )

        partner_id = (
            (sale_owner or {}).get("sold_by_partner")
            or (lot_supplier_owner or {}).get("supplier__partner")
            or (lot_payer or {}).get("paid_by_partner")
            or fallback_partner_id
        )
        if partner_id:
            product.partner_id = partner_id
            product.save(update_fields=["partner"])


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_product_recovery_price_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='product',
            name='uniq_active_product_sku',
        ),
        migrations.RemoveConstraint(
            model_name='supplier',
            name='uniq_active_supplier_name',
        ),
        migrations.AddField(
            model_name='product',
            name='partner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='products', to='core.partner'),
        ),
        migrations.RunPython(backfill_partner_ownership, noop_reverse),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.UniqueConstraint(condition=models.Q(('active', True)), fields=('partner', 'sku'), name='uniq_active_partner_product_sku'),
        ),
        migrations.AddConstraint(
            model_name='supplier',
            constraint=models.UniqueConstraint(condition=models.Q(('active', True)), fields=('partner', 'name'), name='uniq_active_partner_supplier_name'),
        ),
    ]
